//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowCarrierModule.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowCarrierModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Tool 的當地語系化字串。
        /// </summary>
        public static string ClassifyTool {
            get {
                return ResourceManager.GetString("ClassifyTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ConnectionState 的當地語系化字串。
        /// </summary>
        public static string ConnectionForm {
            get {
                return ResourceManager.GetString("ConnectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dec Timeout 的當地語系化字串。
        /// </summary>
        public static string DecTimeoutAlarm {
            get {
                return ResourceManager.GetString("DecTimeoutAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load Timeout , please check ... 的當地語系化字串。
        /// </summary>
        public static string LoadTimeoutAlarm {
            get {
                return ResourceManager.GetString("LoadTimeoutAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Out Alarm 的當地語系化字串。
        /// </summary>
        public static string ProductOutAlarm {
            get {
                return ResourceManager.GetString("ProductOutAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop Timeout 的當地語系化字串。
        /// </summary>
        public static string StopTimeoutAlarm {
            get {
                return ResourceManager.GetString("StopTimeoutAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TCPIPTest 的當地語系化字串。
        /// </summary>
        public static string TCPIPForm {
            get {
                return ResourceManager.GetString("TCPIPForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TopSV Timeout 的當地語系化字串。
        /// </summary>
        public static string TopSVTimeAlarm {
            get {
                return ResourceManager.GetString("TopSVTimeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VacuumSettingState 的當地語系化字串。
        /// </summary>
        public static string VacuumSettingForm {
            get {
                return ResourceManager.GetString("VacuumSettingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vacuum Timeout 的當地語系化字串。
        /// </summary>
        public static string VacuumTimeAlarm {
            get {
                return ResourceManager.GetString("VacuumTimeAlarm", resourceCulture);
            }
        }
    }
}
