//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionModule.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InspectionModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap _3d_printer {
            get {
                object obj = ResourceManager.GetObject("_3d_printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Inspection Data timeout.(Choose &quot;是(Yes)&quot;:Retray waiting data . ；Choose &quot;否(No)&quot;: This tray retry to inspect. ； Choose &quot;取消(Cancel)&quot;: Ignore this Inspection.) 的當地語系化字串。
        /// </summary>
        public static string Alarm_DataTimeout {
            get {
                return ResourceManager.GetString("Alarm_DataTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vision connect failed，Click OK to reconnect，if connection is not online，Please reopen application and check  disk memory. 的當地語系化字串。
        /// </summary>
        public static string Alarm_OnlineFailed {
            get {
                return ResourceManager.GetString("Alarm_OnlineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sgCommands is null. 的當地語系化字串。
        /// </summary>
        public static string Alarm_sgCommands為空 {
            get {
                return ResourceManager.GetString("Alarm_sgCommands為空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SG fail. 的當地語系化字串。
        /// </summary>
        public static string Alarm_SgFailed {
            get {
                return ResourceManager.GetString("Alarm_SgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Grab image Timeout. Does Inspection retry? (Yes:Retry Inspection.，No:Pass Inspection Result and Flow.)(Camera will reconnect) 的當地語系化字串。
        /// </summary>
        public static string Alarm_取像Timeout {
            get {
                return ResourceManager.GetString("Alarm_取像Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Alarm 的當地語系化字串。
        /// </summary>
        public static string Cap_Alarm {
            get {
                return ResourceManager.GetString("Cap_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check the production status. 的當地語系化字串。
        /// </summary>
        public static string CheckProductStatus {
            get {
                return ResourceManager.GetString("CheckProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tool 的當地語系化字串。
        /// </summary>
        public static string ClassifyTool {
            get {
                return ResourceManager.GetString("ClassifyTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap data_analysis {
            get {
                object obj = ResourceManager.GetObject("data_analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Double_Arrow {
            get {
                object obj = ResourceManager.GetObject("Double_Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 APS_TestForm 的當地語系化字串。
        /// </summary>
        public static string gpBtn_APS_TestForm {
            get {
                return ResourceManager.GetString("gpBtn_APS_TestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tool 的當地語系化字串。
        /// </summary>
        public static string gpBtn_ASPTool {
            get {
                return ResourceManager.GetString("gpBtn_ASPTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BarcodeTestForm 的當地語系化字串。
        /// </summary>
        public static string gpBtn_BarcodeTestForm {
            get {
                return ResourceManager.GetString("gpBtn_BarcodeTestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tool 的當地語系化字串。
        /// </summary>
        public static string gpBtn_BarcodeTool {
            get {
                return ResourceManager.GetString("gpBtn_BarcodeTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Statistic Counts 的當地語系化字串。
        /// </summary>
        public static string gpBtn_StatisticCounts {
            get {
                return ResourceManager.GetString("gpBtn_StatisticCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Statistic 的當地語系化字串。
        /// </summary>
        public static string gpTop_Statistic {
            get {
                return ResourceManager.GetString("gpTop_Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Golden3DTeach 的當地語系化字串。
        /// </summary>
        public static string Icon_Golden3DInspect {
            get {
                return ResourceManager.GetString("Icon_Golden3DInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GoldenInspect 的當地語系化字串。
        /// </summary>
        public static string Icon_GoldenInspect {
            get {
                return ResourceManager.GetString("Icon_GoldenInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GoldenTeach 的當地語系化字串。
        /// </summary>
        public static string Icon_GoldenTeach {
            get {
                return ResourceManager.GetString("Icon_GoldenTeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reject Number has reached the set value 的當地語系化字串。
        /// </summary>
        public static string RejectNumberReach {
            get {
                return ResourceManager.GetString("RejectNumberReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This Lot 的當地語系化字串。
        /// </summary>
        public static string TheLot {
            get {
                return ResourceManager.GetString("TheLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap up_down {
            get {
                object obj = ResourceManager.GetObject("up_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
