//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationModule.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalibrationModule.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Image Cross Center Calibration 的當地語系化字串。
        /// </summary>
        public static string CrossCenter {
            get {
                return ResourceManager.GetString("CrossCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Calibration 的當地語系化字串。
        /// </summary>
        public static string Icon_Calibration {
            get {
                return ResourceManager.GetString("Icon_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Camera Calibration 的當地語系化字串。
        /// </summary>
        public static string Icon_CameraCalibration {
            get {
                return ResourceManager.GetString("Icon_CameraCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Laser Calibration 的當地語系化字串。
        /// </summary>
        public static string Icon_LaserCalibration {
            get {
                return ResourceManager.GetString("Icon_LaserCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Light Calibration 的當地語系化字串。
        /// </summary>
        public static string Icon_LightCalibration {
            get {
                return ResourceManager.GetString("Icon_LightCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mosaic Calibration 的當地語系化字串。
        /// </summary>
        public static string Icon_MosaicCalibration {
            get {
                return ResourceManager.GetString("Icon_MosaicCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shade Correction 的當地語系化字串。
        /// </summary>
        public static string Icon_ShadeCorrection {
            get {
                return ResourceManager.GetString("Icon_ShadeCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Laser {
            get {
                object obj = ResourceManager.GetObject("Laser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap mosaic {
            get {
                object obj = ResourceManager.GetObject("mosaic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ShadeCorrection {
            get {
                object obj = ResourceManager.GetObject("ShadeCorrection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap street_light {
            get {
                object obj = ResourceManager.GetObject("street_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
