//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AroundIOModule.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AroundIOModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Tool 的當地語系化字串。
        /// </summary>
        internal static string ClassifyTool {
            get {
                return ResourceManager.GetString("ClassifyTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap customer_support {
            get {
                object obj = ResourceManager.GetObject("customer_support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Door State: Lock 的當地語系化字串。
        /// </summary>
        internal static string DoorLock {
            get {
                return ResourceManager.GetString("DoorLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Door State : Unlock 的當地語系化字串。
        /// </summary>
        internal static string DoorUnlock {
            get {
                return ResourceManager.GetString("DoorUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Idle 的當地語系化字串。
        /// </summary>
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MaintanenceMode 的當地語系化字串。
        /// </summary>
        internal static string MaintanenceMode {
            get {
                return ResourceManager.GetString("MaintanenceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NormalMode 的當地語系化字串。
        /// </summary>
        internal static string NormalMode {
            get {
                return ResourceManager.GetString("NormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProcessForm 的當地語系化字串。
        /// </summary>
        internal static string ProcessForm {
            get {
                return ResourceManager.GetString("ProcessForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Running 的當地語系化字串。
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Safety Mode 的當地語系化字串。
        /// </summary>
        internal static string SafeMode {
            get {
                return ResourceManager.GetString("SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StaticEliminator Alarm,Please Check X066015 的當地語系化字串。
        /// </summary>
        internal static string StaticAlarm {
            get {
                return ResourceManager.GetString("StaticAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StaticEliminator Warning,Please Check X066014 的當地語系化字串。
        /// </summary>
        internal static string StaticWarning {
            get {
                return ResourceManager.GetString("StaticWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 D:\HTASource\LI3000Modules\AroundIOModule\Resources\customer-support.png 的當地語系化字串。
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UnInitial 的當地語系化字串。
        /// </summary>
        internal static string Uninitial {
            get {
                return ResourceManager.GetString("Uninitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unlock 的當地語系化字串。
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
    }
}
